import { Injectable } from '@angular/core';
import { Days } from '../../enums/days';
import { Lesson } from '../../types/lesson';

@Injectable({
  providedIn: 'root',
})
export class LessonsService {
  constructor() {}

  lessons: Lesson[] = [
    {
      id: 1,
      lessonName: 'Yoga',
      teacherName: 'Anna Smith',
      numLessons: 10,
      startDate: new Date('2023-10-01'),
      price: 150,
      day: Days.Monday,
      hour: '18:00',
    },
    {
      id: 2,
      lessonName: 'Pilates',
      teacherName: 'John Doe',
      numLessons: 8,
      startDate: new Date('2023-10-05'),
      price: 120,
      day: Days.Wednesday,
      hour: '19:00',
    },
    {
      id: 3,
      lessonName: 'Zumba',
      teacherName: 'Emily Johnson',
      numLessons: 12,
      startDate: new Date('2023-10-10'),
      price: 180,
      day: Days.Friday,
      hour: '10:00',
    },
    {
      id: 4,
      lessonName: "Women's Sports Class",
      teacherName: 'Miriam Cohen',
      numLessons: 8,
      startDate: new Date('2025-10-05'),
      price: 100,
      day: Days.Sunday,
      hour: '10:00',
    },
    {
      id: 5,
      lessonName: 'Line Dance Class',
      teacherName: 'Rivka Friedman',
      numLessons: 10,
      startDate: new Date('2023-10-02'),
      price: 120,
      day: Days.Monday,
      hour: '17:00',
    },
    {
      id: 6,
      lessonName: 'Private Swimming Lessons',
      teacherName: 'Yossi Levi',
      numLessons: 6,
      startDate: new Date('2023-10-03'),
      price: 150,
      day: Days.Tuesday,
      hour: '15:00',
    },
    {
      id: 7,
      lessonName: "Women's Fitness Class",
      teacherName: 'Sarah Weiss',
      numLessons: 12,
      startDate: new Date('2025-10-12'),
      price: 130,
      day: Days.Thursday,
      hour: '16:00',
    },
    {
      id: 8,
      lessonName: 'Stretching and Flexibility',
      teacherName: 'Noa Ben-David',
      numLessons: 10,
      startDate: new Date('2023-11-01'),
      price: 110,
      day: Days.Wednesday,
      hour: '08:00',
    },
    {
      id: 9,
      lessonName: 'Core Strength Training',
      teacherName: 'Leah Goldstein',
      numLessons: 12,
      startDate: new Date('2025-11-03'),
      price: 130,
      day: Days.Friday,
      hour: '09:00',
    },
    {
      id: 10,
      lessonName: 'Morning Walk & Talk',
      teacherName: 'Rina Adler',
      numLessons: 6,
      startDate: new Date('2023-10-20'),
      price: 60,
      day: Days.Sunday,
      hour: '07:30',
    },
    {
      id: 11,
      lessonName: 'Tai Chi Basics',
      teacherName: 'Gila Rosen',
      numLessons: 8,
      startDate: new Date('2023-11-10'),
      price: 140,
      day: Days.Monday,
      hour: '19:00',
    },
    {
      id: 12,
      lessonName: 'Evening Relaxation Yoga',
      teacherName: 'Batya Levi',
      numLessons: 10,
      startDate: new Date('2023-11-08'),
      price: 150,
      day: Days.Wednesday,
      hour: '20:00',
    },
    {
      id: 13,
      lessonName: 'Aerobic Dance',
      teacherName: 'Shira Green',
      numLessons: 9,
      startDate: new Date('2023-10-28'),
      price: 100,
      day: Days.Tuesday,
      hour: '18:30',
    },
    {
      id: 14,
      lessonName: 'Beginner’s Kickboxing',
      teacherName: 'Etty Mizrachi',
      numLessons: 6,
      startDate: new Date('2023-10-25'),
      price: 120,
      day: Days.Thursday,
      hour: '17:00',
    },
    {
      id: 15,
      lessonName: 'Chair Exercises for Seniors',
      teacherName: 'Esther Braun',
      numLessons: 10,
      startDate: new Date('2025-10-15'),
      price: 80,
      day: Days.Monday,
      hour: '11:00',
    },
    {
      id: 16,
      lessonName: 'Fitness Bootcamp',
      teacherName: 'Tamar Shalom',
      numLessons: 8,
      startDate: new Date('2023-11-12'),
      price: 140,
      day: Days.Sunday,
      hour: '17:30',
    },
    {
      id: 17,
      lessonName: 'Dance for Health',
      teacherName: 'Michal Levy',
      numLessons: 12,
      startDate: new Date('2023-11-01'),
      price: 130,
      day: Days.Thursday,
      hour: '18:00',
    },
    {
      id: 18,
      lessonName: 'Prenatal Yoga',
      teacherName: 'Avigail Cohen',
      numLessons: 6,
      startDate: new Date('2023-10-18'),
      price: 120,
      day: Days.Tuesday,
      hour: '10:00',
    },
    {
      id: 19,
      lessonName: 'Back Care Class',
      teacherName: 'Orly Sharabi',
      numLessons: 8,
      startDate: new Date('2023-10-22'),
      price: 110,
      day: Days.Sunday,
      hour: '09:00',
    },
    {
      id: 20,
      lessonName: 'Functional Movement',
      teacherName: 'Dafna Harari',
      numLessons: 10,
      startDate: new Date('2025-11-04'),
      price: 140,
      day: Days.Wednesday,
      hour: '19:00',
    },
    {
      id: 21,
      lessonName: 'Posture & Balance',
      teacherName: 'Tzippy Manor',
      numLessons: 10,
      startDate: new Date('2024-10-30'),
      price: 100,
      day: Days.Monday,
      hour: '14:00',
    },
    {
      id: 22,
      lessonName: 'Mindful Movement',
      teacherName: 'Yehudit Azulay',
      numLessons: 8,
      startDate: new Date('2023-11-07'),
      price: 90,
      day: Days.Tuesday,
      hour: '08:30',
    },
    {
      id: 23,
      lessonName: 'Strength for Women',
      teacherName: 'Hadas Kaplan',
      numLessons: 10,
      startDate: new Date('2023-10-19'),
      price: 130,
      day: Days.Thursday,
      hour: '09:30',
    },
    {
      id: 24,
      lessonName: 'Healthy Shoulders',
      teacherName: 'Naama Ben-Sasson',
      numLessons: 6,
      startDate: new Date('2023-11-06'),
      price: 85,
      day: Days.Monday,
      hour: '13:00',
    },
    {
      id: 25,
      lessonName: 'Balance & Agility',
      teacherName: 'Zehava Keren',
      numLessons: 8,
      startDate: new Date('2025-10-27'),
      price: 100,
      day: Days.Friday,
      hour: '11:00',
    },
    {
      id: 26,
      lessonName: 'Body Awareness',
      teacherName: 'Rachel Stern',
      numLessons: 10,
      startDate: new Date('2023-11-15'),
      price: 120,
      day: Days.Wednesday,
      hour: '16:00',
    },
    {
      id: 27,
      lessonName: 'Light Cardio',
      teacherName: 'Nava Biton',
      numLessons: 9,
      startDate: new Date('2023-10-26'),
      price: 95,
      day: Days.Thursday,
      hour: '10:00',
    }
  ];

  getLessons() {
    return this.lessons;
  }

  getLessonById(id: number): Lesson | undefined {
    return this.lessons.find((lesson) => lesson.id === id);
  }
}
